version: '3.8'

services:
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
    networks:
      - emllm-network

  bot-generator:
    build: ./bot-generator
    depends_on:
      - mailhog
    environment:
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - FROM_EMAIL=bot@example.com
      - TO_EMAIL=llm@example.com
    networks:
      - emllm-network

  camel-server:
    build: ./camel-server
    depends_on:
      - mailhog
      - ollama
    environment:
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - IMAP_HOST=mailhog
      - IMAP_PORT=1143
      - IMAP_USER=llm@example.com
      - IMAP_PASSWORD=password
      - OLLAMA_BASE_URL=http://ollama:11434
      - SERVER_PORT=8080
    ports:
      - "${API_PORT:-8087}:8080"
    volumes:
      - ./data/emails:/app/emails
    networks:
      - emllm-network

  client-agent:
    build: ./client-agent
    depends_on:
      - mailhog
    environment:
      - IMAP_HOST=mailhog
      - IMAP_PORT=1143
      - IMAP_USER=client@example.com
      - IMAP_PASSWORD=password
      - DEPLOYMENT_DIR=/app/deployments
    volumes:
      - ./deployments:/app/deployments
    networks:
      - emllm-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - emllm-network

  web-ui:
    build: ./web-ui
    ports:
      - "${WEB_UI_PORT:-3003}:3000"
    depends_on:
      - camel-server
    networks:
      - emllm-network

networks:
  emllm-network:
    driver: bridge

volumes:
  ollama_data:
